"""
backtest_new_gate.py — replay resolved Phase 1 signals under the proposed
gate (model_prob - market_price >= 0.08 AND model_prob >= 0.55) and compare
to the prior price-cap rule (market_price < 0.30).

LIMITATIONS — read before interpreting results:

  1. Phase 1 signals were generated by the pre-fix forecast pipeline whose
     calibration was inverted (predict 5% → actual 43%, predict 35% → actual
     18%). Replaying the new gate against these probabilities does NOT tell
     us what the post-fix bot will do — it tells us what the OLD bot would
     have done with the new gate. Treat as a sanity check on rule shape,
     not a return forecast.

  2. Phase 1 fires in the morning from forecast data; Phase 2 fires at lock
     time from running_max. Probabilities are computed differently. This
     backtest only approximates Phase 2 behavior — Phase 2 probabilities
     post-lock tend to be much higher (we're observing the day's peak).

  3. Oracle-bug-affected rows (Polymarket 2026-05-18/19 disclosure) are
     excluded — Miami/Mexico City/Seoul/Hong Kong on 2026-05-17 and any
     market with winning_bracket='VOIDED'.

  4. Simulated $15 position size per trade. Real bot would scale by edge.
"""
import os
import sys
from collections import defaultdict
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(dotenv_path=Path("/root/polymarket/.env"))
from supabase import create_client  # noqa: E402

url = os.environ.get("VITE_SUPABASE_URL") or os.environ["SUPABASE_URL"]
sb = create_client(url, os.environ["SUPABASE_SERVICE_KEY"])

ORACLE_BUG = {
    ("Miami", "2026-05-17"),
    ("Mexico City", "2026-05-17"),
    ("Seoul", "2026-05-17"),
    ("Hong Kong", "2026-05-17"),
}

TRADE_SIZE = 15.0
NEW_EDGE = 0.08
NEW_MIN_PROB = 0.55
OLD_MAX_PRICE = 0.30


def fetch_rows():
    out = []
    page = 0
    while True:
        r = (sb.table("trade_signals")
             .select("forecast_date,city,side,market_price,model_probability,"
                     "actual_outcome,winning_bracket,outcome")
             .eq("signal_phase", "phase1")
             .not_.is_("winning_bracket", "null")
             .not_.is_("model_probability", "null")
             .not_.is_("market_price", "null")
             .not_.eq("winning_bracket", "VOIDED")
             .range(page * 1000, (page + 1) * 1000 - 1)
             .execute())
        if not r.data:
            break
        out.extend(r.data)
        if len(r.data) < 1000:
            break
        page += 1
    return out


def simulate(rows, predicate, label):
    fires = 0
    wins = 0
    pnl = 0.0
    prices = []
    by_side = defaultdict(lambda: [0, 0, 0.0])  # fires, wins, pnl
    by_prob_bin = defaultdict(lambda: [0, 0])    # fires, wins
    for r in rows:
        if not predicate(r):
            continue
        fires += 1
        p = r["market_price"]
        won = (r.get("actual_outcome") == "true")
        if won:
            wins += 1
            pnl += TRADE_SIZE * (1.0 - p) / p
        else:
            pnl -= TRADE_SIZE
        prices.append(p)
        side = r.get("side") or "?"
        by_side[side][0] += 1
        by_side[side][1] += int(won)
        by_side[side][2] += (TRADE_SIZE * (1.0 - p) / p) if won else -TRADE_SIZE
        mp = r.get("model_probability") or 0
        bin_ = round(mp * 10) / 10  # nearest 0.1
        by_prob_bin[bin_][0] += 1
        by_prob_bin[bin_][1] += int(won)

    win_rate = (wins / fires) if fires else 0.0
    avg_price = (sum(prices) / len(prices)) if prices else 0.0
    print(f"\n=== {label} ===")
    print(f"  trades fired:     {fires}")
    print(f"  wins / losses:    {wins} / {fires - wins}")
    print(f"  win rate:         {win_rate:.1%}")
    print(f"  simulated P&L:    ${pnl:+.2f}  (size ${TRADE_SIZE}/trade)")
    print(f"  P&L per trade:    ${pnl/fires:+.2f}" if fires else "  no trades")
    print(f"  avg buy price:    {avg_price:.3f}")
    if prices:
        prices_sorted = sorted(prices)
        q = lambda f: prices_sorted[int(len(prices_sorted) * f)]
        print(f"  price distribution: p10={q(0.10):.2f}  p25={q(0.25):.2f}  "
              f"p50={q(0.50):.2f}  p75={q(0.75):.2f}  p90={q(0.90):.2f}")
    print(f"  by side:")
    for side, (f, w, p) in by_side.items():
        print(f"    {side}: trades={f}  wins={w}  rate={(w/f):.1%}  pnl=${p:+.2f}" if f else f"    {side}: 0")
    print(f"  by model_prob bin (calibration check):")
    for b in sorted(by_prob_bin):
        f, w = by_prob_bin[b]
        if f >= 5:
            print(f"    {b:.1f}: n={f}  actual_win_rate={(w/f):.1%}")


def main():
    rows = fetch_rows()
    # Filter oracle-bug
    pre = len(rows)
    rows = [r for r in rows if (r.get("city"), r.get("forecast_date")) not in ORACLE_BUG]
    print(f"fetched {pre} resolved Phase 1 rows; after oracle-bug filter: {len(rows)}")
    dates = sorted({r["forecast_date"] for r in rows})
    print(f"date range: {dates[0]} -> {dates[-1]}  ({len(dates)} dates)")
    cities = sorted({r["city"] for r in rows})
    print(f"cities: {len(cities)}")

    # Overall calibration (no gate)
    print("\n=== Calibration audit (no gate, all rows) ===")
    bin_counts = defaultdict(lambda: [0, 0])
    for r in rows:
        mp = r.get("model_probability") or 0
        bin_ = round(mp * 10) / 10
        bin_counts[bin_][0] += 1
        if r.get("actual_outcome") == "true":
            bin_counts[bin_][1] += 1
    print("  predicted | n     | actual_win_rate")
    for b in sorted(bin_counts):
        n, w = bin_counts[b]
        if n >= 10:
            print(f"  {b:0.1f}      | {n:5d} | {(w/n):.1%}")

    # OLD price-cap rule (YES side, market_price < 0.30, positive edge)
    simulate(rows,
             lambda r: r["side"] == "YES"
                       and r["market_price"] < OLD_MAX_PRICE
                       and (r["model_probability"] - r["market_price"]) > 0,
             label="OLD rule: YES, price<0.30, positive edge")

    # NEW gate
    simulate(rows,
             lambda r: (r["model_probability"] - r["market_price"]) >= NEW_EDGE
                       and r["model_probability"] >= NEW_MIN_PROB,
             label=f"NEW gate: edge>={NEW_EDGE}, model_prob>={NEW_MIN_PROB} (BOTH sides)")

    # NEW gate restricted to YES side only
    simulate(rows,
             lambda r: r["side"] == "YES"
                       and (r["model_probability"] - r["market_price"]) >= NEW_EDGE
                       and r["model_probability"] >= NEW_MIN_PROB,
             label=f"NEW gate, YES only")

    # NEW gate restricted to NO side only — "expanded sweep" proxy
    simulate(rows,
             lambda r: r["side"] == "NO"
                       and (r["model_probability"] - r["market_price"]) >= NEW_EDGE
                       and r["model_probability"] >= NEW_MIN_PROB,
             label=f"NEW gate, NO only (sweep proxy)")

    # Sensitivity: what if we use 5pp instead of 8pp?
    simulate(rows,
             lambda r: (r["model_probability"] - r["market_price"]) >= 0.05
                       and r["model_probability"] >= 0.55,
             label="SENSITIVITY: edge>=0.05, model_prob>=0.55")

    # Sensitivity: what if we use 10pp?
    simulate(rows,
             lambda r: (r["model_probability"] - r["market_price"]) >= 0.10
                       and r["model_probability"] >= 0.55,
             label="SENSITIVITY: edge>=0.10, model_prob>=0.55")


if __name__ == "__main__":
    main()
